### ISSUE TITLE
not compatible with Ulauncher v5.3.0

### ISSUE THREAD

**Issue by lebedov** [beajeanm/ulauncher-windows-switcher#2] opened 2019-05-13 18:07 UTC
The latest revision of the extension doesn't appear to work with Ulauncher v5.3.0.

**Comment by williamjosh** [comment] 2019-06-07 07:25
Can someone fix it, please?

**Comment by williamjosh** [comment] 2019-06-07 07:29
Can somebody fix it, please?

**Comment by nblavoie** [comment] 2019-10-08 02:02
I will try to fix the problem. I'll keep you posted.

**Comment by Auniik** [comment] 2019-10-18 10:17
not compatible with Ulauncher v5.3.0

**Comment by delucca** [comment] 2019-11-12 17:16
Any updates on this?

**Comment by neikei** [comment] 2019-11-24 15:04
I tried to migrate the extension with the [official migration guide](http://docs.ulauncher.io/en/latest/extensions/migration.html), but the extension hangs in "Loading..." now. Unfortunately I am not a python developer. So I don't know if the following output is related and how to fix it.

```bash
[neikei@EndeavourOS-PC ~]$ ulauncher -v
...
2019-11-24 15:59:35,185 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "ulauncher-windows-switcher"
ulauncher-windows-switcher | 2019-11-24 15:59:35,186 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2019-11-24 15:59:37,993 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 4 results
2019-11-24 15:59:38,034 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 2 results
2019-11-24 15:59:42,520 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event KeywordQueryEvent to "ulauncher-windows-switcher"
ulauncher-windows-switcher | 2019-11-24 15:59:42,602 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event KeywordQueryEvent
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ulauncher/api/client/Client.py", line 54, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python3.8/site-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/neikei/.local/share/ulauncher/extensions/ulauncher-windows-switcher/main.py", line 96, in on_event
    extension.items = [WindowItem(window, extension.previous_selection) for window in list_windows()]
  File "/home/neikei/.local/share/ulauncher/extensions/ulauncher-windows-switcher/main.py", line 96, in <listcomp>
    extension.items = [WindowItem(window, extension.previous_selection) for window in list_windows()]
  File "/home/neikei/.local/share/ulauncher/extensions/ulauncher-windows-switcher/main.py", line 52, in __init__
    self.icon = self.retrieve_or_save_icon(window.get_icon())
  File "/home/neikei/.local/share/ulauncher/extensions/ulauncher-windows-switcher/main.py", line 57, in retrieve_or_save_icon
    file_name = hashlib.sha224(self.app_name).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by rabin-io** [comment] 2019-11-24 15:58
you can test [my fork](https://github.com/rabin-io/ulauncher-windows-switcher/tree/python3) for now, I also submitted [PR](https://github.com/beajeanm/ulauncher-windows-switcher/pull/3) for it.

**Comment by KuenzelIT** [comment] 2019-12-05 22:57
I cannot install the extension, seems like a `versions.json` is missing in both repos, the main one and the fork of @rabin-io :

```bash
2019-12-05 23:55:17,825 | WARNING | ulauncher.api.server.GithubExtension: _read_json() | _read_json("master", "versions.json") failed. HTTPError: HTTP Error 404: Not Found
2019-12-05 23:55:17,826 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | GithubExtensionError: Could not find versions.json file using URL "https://raw.githubusercontent.com/rabin-io/ulauncher-windows-switcher/master/versions.json"
```

Does anyone have an idea if the versions.json is required?

**Comment by neikei** [comment] 2019-12-06 07:36
@KuenzelIT, the fix is only available in the python3 branch and not in the master branch. I tested the python3 branch on Linux and it worked great.

**Comment by KuenzelIT** [comment] 2019-12-07 11:38
I don't see a python3 branch in this repository. Am I missing something?

**Comment by rabin-io** [comment] 2019-12-07 20:15
It's in my repo 

https://github.com/rabin-io/ulauncher-windows-switcher/tree/python3

**Comment by KuenzelIT** [comment] 2019-12-08 11:56
Hey, I tested your fix and it works to get a list of open windows an selecting them with the arrow keys, but the search has a really strange bug. If I type any character of "Firefox", the search works and lists my Firefox windows. If I use any other character it keeps loading and I get the following error:

```
ulauncher-windows-switcher | 2019-12-08 12:52:25,716 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event KeywordQueryEvent
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Client.py", line 54, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/kuenzel/.local/share/ulauncher/extensions/ulauncher-windows-switcher/main.py", line 97, in on_event
    matching_items = [window_item.to_extension_item() for window_item in extension.items if
  File "/home/kuenzel/.local/share/ulauncher/extensions/ulauncher-windows-switcher/main.py", line 98, in <listcomp>
    window_item.is_matching(query)]
  File "/home/kuenzel/.local/share/ulauncher/extensions/ulauncher-windows-switcher/main.py", line 73, in is_matching
    return ascii_keyword in self.app_name.encode('ascii').lower() or ascii_keyword in self.title.encode('ascii').lower()
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 6: ordinal not in range(128)
```

**Comment by KuenzelIT** [comment] 2019-12-08 17:46
I looked into it and the problem is the encoding of the german umlaut "ü" to ascii. I removed the ascii encoding and now it works as expected:

```python
    def is_matching(self, keyword):
        if keyword == "":
            return True

        keyword = keyword.lower()
        app_name = self.app_name.lower()
        title = self.title.lower()

        return keyword in app_name or keyword in title
```

Can you fix this in your fork and create a pull request? Is there a reason why you added the ascii encoding to check for matching windows?

Thanks for your work, the extension is awesome when having a lot of windows open across multiple virtual desktops.

**Comment by rabin-io** [comment] 2019-12-08 19:46
I committed a fix to use UTF-8 encoding.

**Comment by KuenzelIT** [comment] 2019-12-08 20:46
Thank you!

**Comment by lwbaqueros** [comment] 2020-09-06 22:00
![Screenshot from 2020-09-06 23-59-45](https://user-images.githubusercontent.com/46763074/92336063-102ae600-f09d-11ea-991e-78484f85c630.png)

I have still this problem

**Comment by rabin-io** [comment] 2020-09-07 09:11
@lwbaqueros My PR was not merged yet, so you will need to use my repo url for now

https://github.com/rabin-io/ulauncher-windows-switcher/tree/python3

**Comment by lwbaqueros** [comment] 2020-09-07 15:09
@rabin-io Thanks. It works perfectly. I added the extention with this URL: [https://github.com/rabin-io/ulauncher-windows-switcher/](https://github.com/rabin-io/ulauncher-windows-switcher)

**Closed as completed** 2022-08-04 22:51 UTC
